language: sh
script: make test
os:
  - linux
  - osx
notifications:
  slack:
    rooms:
      secure: x1P4VnLS76/HEpgr2DQu83G9fuJ6Nww3Yfcn35it0w+NTWkG5UYBwH5qly8z/OzKNYdhRMIvUvMom5ALh7eCmIUWxyl5dhzq5vSIyMrq5SW0C6Bq4xxuj+iB8sQ4bs8PTag/phHC3ZpNy9F6iYSR0uL9Ne1ayydW5h8UiLMvpr93uF3jP+a16iKGk16oD2iqYUCLRD830KUzpD077nTEZ1KxBv4mP/3Sba3cio1FWGBr4i82xp0n9K+EZzb790gNbz4x5EuQOZjUFL0ks4WO6+Oz/Ky0cFvaLXoRwI73aTTFSHlVyHI7lD13cDrzhcLTSq1cfzvfhWeoxaULan2VumfBu8dshU5k2eYnSSY6irVbMoWNa3R1ckwx8qbglWzWZuvqsE33FrG3gesUVPYUKMtR43NCsu/uxRael4FgicMT75e8k66ArFy+hZFurriuBuddtTXkk95AUY1uLUt8f3u8GL/JnsIt+qmQ2fq9tRMsV4VGDuNk7n6/6AKInQs4txujUyglc0zxl989gGZaGOUw2P2wqrmZv00n3Fp5goj8LG7wIDUPPiMAgO/vy+qhqjBVktthGE5jORfNJoJrXmipxX0GyYcQCIbmodjwjOQBw79s5sq0UyeIhx+EQuPnvsTwNwM2kVbQ/dv2dsy+6pdB5etHR8L2o5ZO1M+9HuU=
